### ISSUE TITLE
Can you help me interpret this memcheck output?

### ISSUE THREAD

**Issue by rmosolgo** [Shopify/ruby_memcheck#14]
Hi! Thanks for your work on this gem. I'm pursuing a Bison-based GraphQL parser over in https://github.com/rmosolgo/graphql-ruby/pull/4368, so I thought I'd give this library a try. I enabled it on GitHub Actions ([example](https://github.com/rmosolgo/graphql-ruby/actions/runs/4533528143/jobs/7986461617?pr=4368)) but I'm not quite sure how to make sense of the output. Here are a few stack traces: 

```

Invalid write of size 8
  vm_exec_core (vm.inc:1028)
  rb_vm_exec (vm.c:1929)
  rb_vm_call0 (vm_eval.c:52)
  rb_vm_call_kw (vm_eval.c:268)
  method_missing (vm_eval.c:874)
  rb_call0 (vm_eval.c:389)
  send_internal (vm_eval.c:1135)
  send_internal_kw (vm_eval.c:1158)
  rb_f_public_send (vm_eval.c:1210)
  vm_call_cfunc_with_frame (vm_insnhelper.c:2514)
  vm_call_cfunc (vm_insnhelper.c:2539)
  vm_sendish (vm_insnhelper.c:4023)
  vm_exec_core (insns.def:801)
  rb_vm_exec (vm.c:1929)
  rb_fiber_start (cont.c:1830)
  fiber_entry (cont.c:694)

Invalid read of size 8
  imemo_type (internal.h:1150)
  rb_vm_make_proc_lambda (vm.c:946)
  rb_vm_make_lambda (vm_core.h:1671)
  rb_mod_define_method (proc.c:2062)
  vm_call_cfunc_with_frame (vm_insnhelper.c:2514)
  vm_call_cfunc (vm_insnhelper.c:2539)
  vm_sendish (vm_insnhelper.c:4023)
  vm_exec_core (insns.def:782)
  rb_vm_exec (vm.c:1929)
  rb_vm_call0 (vm_eval.c:52)
  rb_vm_call_kw (vm_eval.c:268)
  method_missing (vm_eval.c:874)
  rb_call0 (vm_eval.c:389)
  send_internal (vm_eval.c:1135)
  send_internal_kw (vm_eval.c:1158)
  rb_f_public_send (vm_eval.c:1210)
  vm_call_cfunc_with_frame (vm_insnhelper.c:2514)
  vm_call_cfunc (vm_insnhelper.c:2539)
  vm_sendish (vm_insnhelper.c:4023)
  vm_exec_core (insns.def:801)
  rb_vm_exec (vm.c:1929)
  rb_fiber_start (cont.c:1830)
  fiber_entry (cont.c:694)

Invalid read of size 1
  vm_ic_hit_p (vm_insnhelper.c:4131)
  vm_exec_core (insns.def:1042)
  <unknown stack frame>
  rb_vm_exec (vm.c:1929)
  rb_fiber_start (cont.c:1830)
  fiber_entry (cont.c:694)
```

All the entries in these files point to Ruby internals. Does that mean they're false positives? Or, should I keep digging based on these? 

Thanks for taking a look!

**Comment by peterzhu2118** [comment]
Hello! This gem will only filter memory leaks and always output invalid memory accesses (since under normal operation, Ruby should never access invalid memory). I see that you're running on Ruby 2.7, which will be EOL very soon. Can you reproduce these issues on a newer version of Ruby (preferably on 3.2.1).

**Comment by rmosolgo** [comment]
Thanks for checking it out -- I'll keep an eye out about that release!

**Comment by rmosolgo** [comment]
Ok, I think this is "good"! Here's the output from my last run: 

```
200,014 bytes in 2 blocks are definitely lost in loss record 139,468 of 139,600
  malloc (vg_replace_malloc.c:393)
 *yyparse (parser.c:1768)
 *GraphQL_CParser_Parser_c_parse (graphql_c_parser_ext.c:8)
  vm_call_cfunc_with_frame (vm_insnhelper.c:3268)
  ....
```

I suppose this constitutes a real problem -- I'll investigate the generated parser code and see if I can make sense of it. Thanks for your help with this!

Here's the build: https://github.com/rmosolgo/graphql-ruby/actions/runs/4556195698/jobs/8036241668?pr=4410
