### ISSUE TITLE
should ruby_memcheck ignore `stack_chunk_alloc`?

### ISSUE THREAD

**Issue by flavorjones** [Shopify/ruby_memcheck#6]
Recently I've seen quite a few ruby_memcheck failures in Nokogiri's test suite related to GC bookkeeping that I think the gem should ignore.

The stack walkback is something like:

```
# 52,104 (4,008 direct, 48,096 indirect) bytes in 1 blocks are definitely lost in loss record 38,778 of 38,821
#   malloc (vg_replace_malloc.c:307)
#   stack_chunk_alloc (gc.c:5917)
#   push_mark_stack_chunk (gc.c:5980)
#   push_mark_stack (gc.c:6038)
#   gc_grey (gc.c:6665)
#   gc_mark (gc.c:6747)
#   gc_mark_children (gc.c:6938)
#   gc_mark_stacked_objects (gc.c:7071)
#   gc_mark_stacked_objects_incremental (gc.c:7105)
#   gc_marks_rest (gc.c:8091)
#   gc_rest (gc.c:8988)
#   gc_rest (gc.c:8976)
#   garbage_collect (gc.c:8847)
#   garbage_collect_with_gvl (gc.c:9225)
#   objspace_malloc_increase_body (gc.c:11298)
#   objspace_malloc_increase_body (gc.c:11276)
#   objspace_malloc_fixup (gc.c:11376)
#   objspace_xmalloc0 (gc.c:11447)
#  *xmlSAX2TextNode (SAX2.c:1840)
#  *xmlSAX2Text (SAX2.c:2617)
#  *xmlParseContentInternal (parser.c:9929)
#  *xmlParseElement (parser.c:9987)
#  *xmlParseDocument (parser.c:10824)
#  *xmlDoRead (parser.c:15171)
#  *read_memory (xml_document.c:331)
```

In this example, the C extension code is calling `ruby_xmalloc` which triggers GC. The GC mark phase allocates memory for internal bookkeeping, which I believe is used as a "free pool" of memory that Ruby doesn't ever free.

In the past I have already tried to suppress these warnings (see https://github.com/sparklemotion/nokogiri/commit/a0360803740e5c85767ace75563bb3a3b33d1963 for an example) but as Ruby continues to evolve these get out of date, or the stack varies slightly.

Some links if you'd like to dig deeper:

- https://github.com/sparklemotion/nokogiri/runs/7474777076?check_suite_focus=true
- https://github.com/sparklemotion/nokogiri/runs/7457816991?check_suite_focus=true
- https://github.com/sparklemotion/nokogiri/runs/7282476570?check_suite_focus=true
- https://github.com/sparklemotion/nokogiri/runs/7310948711?check_suite_focus=true
- https://github.com/sparklemotion/nokogiri/runs/7287062715?check_suite_focus=true

My suggestion would be to consider adding `stack_chunk_alloc` to the list of default skipped ruby functions, but maybe folks with deeper knowledge of Ruby's inner workings have other ideas.

cc @peterzhu2118

**Comment by peterzhu2118** [comment]
I think this should be fixed in ruby/ruby#5536, but this hasn't been backported to any of the current Ruby versions. Perhaps I should open a ticket to backport this patch?

**Comment by flavorjones** [comment]
Ah! I hadn't seen that fix, thank you!

I would vote to have that backported to 3.1, yes.

**Comment by peterzhu2118** [comment]
I opened #7 which can be reverted once the fix is backported and a patch release is made.
